services:

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: veilbid
      POSTGRES_DB: veilbidDB

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:latest

    command:
      - start-dev
      - --db=postgres

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: veilbid

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/veilbidDB
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: veilbid

    ports:
      - "9090:8080"

    depends_on:
      - db

    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  postgres-data:
  keycloak-data: