spring.application.name=veilbid
spring.thymeleaf.cache=false

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=veilbid
spring.datasource.url=jdbc:postgresql://localhost:5433/veilbidDB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect